name: EN
on:
  push:
  workflow_dispatch:
    inputs:
      force_build_so:
        description: 'Force build so without changes'
        type: string
        default: "true"
#   schedule:
#    - cron: '*/60 * * * *'
jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - name: checkout lib
        uses: actions/checkout@v4
        with:
          path: Main
          repository: ${{ secrets.MAIN }}
          ref: 'EN'
          ssh-key: ${{ secrets.SSH_KEY }}
          sparse-checkout: |
            lib

      - name: checkout Apk
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.APK }}
          ssh-key: ${{ secrets.SSH_KEY }}
          path: AzurLaneApk
          ref: EN
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v3.2.1
        with:
          packages: 'platform-tools platforms;android-34 build-tools;34.0.0'
      - name: Output build-tools path and add to PATH
        run: |
          ls -la ${ANDROID_SDK_ROOT}/build-tools/34.0.0
          echo "${ANDROID_SDK_ROOT}/build-tools/34.0.0" >> $GITHUB_PATH
      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          # python-version: # optional
          # Used to specify a package manager for caching in the default directory. Supported values: pip, pipenv, poetry.
          cache: pip

      - name: Build APK
        run: |
          cp -r ../Main/lib/. libs/
          python3 main.py
        working-directory: AzurLaneApk

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # - name: Create Release
      #   uses: ncipollo/release-action@v1.12.0
      #   with:
      #     name: ${{ steps.date.outputs.date }}_EN
      #     allowUpdates: true
      #     artifactErrorsFailBuild: true
      #     artifacts: AzurLaneApk/build/com.YoStarEN.AzurLane.xapk,AzurLaneApk/build/com.YoStarEN.AzurLane.patched.apk
      #     draft: true
      #     #           commit: "latest"
      #     makeLatest: false
      #     tag: "testEN"
      #     omitBody: true
