name: Combined Build
on:
  push:
  workflow_dispatch:
    inputs:
      force_build_so:
        description: 'Force build so without changes'
        type: string
        default: "true"

jobs:
  pre_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [EN, JP]
    outputs:
      should_skip: ${{ steps.check.outputs.should_skip }}
      skip_translate: ${{ steps.check.outputs.skip_translate }}
    steps:
      - id: check
        run: |
          if [ "${{ github.event_name }}" != "workflow_dispatch" ]; then
            echo "skip_translate=false" >> $GITHUB_OUTPUT
            echo "should_skip=false" >> $GITHUB_OUTPUT
          else
            echo "skip_translate=${{ github.event.inputs.force_build_so }}" >> $GITHUB_OUTPUT
            echo "should_skip=false" >> $GITHUB_OUTPUT
          fi

  update_h:
    needs: pre_check
    strategy:
      matrix:
        config: [EN, JP]
    outputs:
      any_translate_changed: ${{ steps.check_changes.outputs.any_translate_changed }}
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v2.0
        with:
          timezoneLinux: "Asia/Singapore"
          timezoneMacos: "Asia/Singapore"
          timezoneWindows: "Singapore Standard Time"
      
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MAIN }}
          ref: ${{ matrix.config }}
          ssh-key: ${{ secrets.SSH_KEY }}
          path: Main
          sparse-checkout: |
            Output
            python

      - name: Checkout AzurLaneLuaScripts
        uses: actions/checkout@v4
        with:
          repository: AzurLaneTools/AzurLaneLuaScripts
          path: AzurLaneLuaScripts
          ref: main
          sparse-checkout: |
            CN/gamecfg/story/
            CN/sharecfg/
            CN/sharecfg/ship_skin_template_sublist/
            CN/sharecfg/enemy_data_statistics_sublist/
            CN/sharecfgdata/
            ${{ matrix.config }}/gamecfg/story${{ matrix.config == 'JP' && 'jp' || '' }}/
            ${{ matrix.config }}/sharecfg/
            ${{ matrix.config }}/sharecfgdata/

      - name: Setup Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          rm -f ../Output/*
          pip install lupa
          python3 tranlator.py
          python3 story.py
          python3 namecode.py
        working-directory: Main/python

      - name: Commit files
        id: check_changes
        working-directory: Main
        run: |
          if ${{ needs.pre_check.outputs.skip_translate == 'true' }} ; then
            echo "any_translate_changed=true" >> $GITHUB_OUTPUT
          else
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config user.name "github-actions[bot]"
            if [[ `git status --porcelain Output` ]]; then
              git add Output
              git commit -m "Changes *.h for ${{ matrix.config }}"
              git push
              echo "any_translate_changed=true" >> $GITHUB_OUTPUT
            else
              echo "No changes to commit"
              echo "any_translate_changed=false" >> $GITHUB_OUTPUT
            fi
            echo "sleep..."
            sleep 10
          fi

  build_so:
    needs: update_h
    if: ${{ needs.update_h.outputs.any_translate_changed == 'true' }}
    strategy:
      matrix:
        config: [EN, JP]
        triplet: [arm64-v8a, armeabi-v7a]
        include:
          - config: EN
            module_name: OceanEN
            apk_ref: EN
          - config: JP
            module_name: OceanJP
            apk_ref: JP
    env:
      VCPKG_BINARY_SOURCES: clear;files,${{ github.workspace }}/AzurLane/build/${{ matrix.triplet }}/vcpkg_installed,readwrite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.MAIN }}
          ref: ${{ matrix.config }}
          submodules: recursive
          path: Main
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Checkout Zygisk
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.ZYGISK }}
          ref: Ocean
          path: AzurLane
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}-${{ matrix.config }}-${{ matrix.triplet }}

      - name: Move files
        run: |
          cp -r Main/Output/*.cpp AzurLane/app/src/main/cpp/azur/src
          cp -r Main/Output/*.h   AzurLane/app/src/main/cpp/azur/src
          echo "MODULE_NAME=${{ matrix.module_name }}" >> $GITHUB_ENV

      - uses: actions/setup-java@v4.7.1
        with:
          distribution: temurin
          java-version: 17

      - uses: lukka/get-cmake@latest

      - name: Restore vcpkg cache
        uses: actions/cache/restore@main
        with:
          path: ${{ github.workspace }}/AzurLane/build/${{ matrix.triplet }}/vcpkg_installed
          key: vcpkg-${{ matrix.config }}-${{ matrix.triplet }}-${{ hashFiles('AzurLane/app/src/main/cpp/vcpkg.json') }}
          restore-keys: vcpkg-${{ matrix.config }}-${{ matrix.triplet }}-

      - uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgJsonGlob: 'AzurLane/app/src/main/cpp/vcpkg.json'
          doNotCache: true

      - name: Run CMake
        uses: lukka/run-cmake@v10
        id: runcmake
        with:
          cmakeListsTxtPath: 'AzurLane/app/src/main/cpp/CMakeLists.txt'
          configurePreset: ${{ matrix.triplet }}
          buildPreset: ${{ matrix.triplet }}
          configurePresetAdditionalArgs: "['-DCMAKE_C_COMPILER_LAUNCHER=ccache','-DCMAKE_CXX_COMPILER_LAUNCHER=ccache']"

      - name: Save vcpkg cache
        uses: actions/cache/save@main
        with:
          path: ${{ github.workspace }}/AzurLane/build/${{ matrix.triplet }}/vcpkg_installed
          key: vcpkg-${{ matrix.config }}-${{ matrix.triplet }}-${{ hashFiles('AzurLane/app/src/main/cpp/vcpkg.json') }}

      - name: Commit SO files
        id: check_so_changed
        working-directory: Main
        run: |
          rm -f lib/${{ matrix.triplet }}/*
          cp ../AzurLane/build/${{ matrix.triplet }}/lib${{ env.MODULE_NAME }}.so lib/${{ matrix.triplet }}
          
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          
          if [[ -z $(git status --porcelain lib) ]]; then
            echo "No changes to commit"
            echo "any_so_changed=false" >> $GITHUB_OUTPUT
          else
            git add lib
            git commit -m "Update ${{ matrix.triplet }} libraries for ${{ matrix.config }}"
            git pull --rebase origin ${{ matrix.config }}
            if git push origin ${{ matrix.config }}; then
              echo "any_so_changed=true" >> $GITHUB_OUTPUT
            else
              echo "any_so_changed=false" >> $GITHUB_OUTPUT
            fi
          fi

  build_apk:
    needs: build_so
    strategy:
      matrix:
        config: [EN, JP]
        include:
          - config: EN
            apk_ref: EN
            app_name: YoStarEN
          - config: JP
            apk_ref: JP
            app_name: YoStarJP
    runs-on: ubuntu-latest
    steps:
      - name: Wait after push
        run: sleep 10

      - name: Checkout lib
        uses: actions/checkout@v4
        with:
          path: Main
          repository: ${{ secrets.MAIN }}
          ref: ${{ matrix.config }}
          ssh-key: ${{ secrets.SSH_KEY }}
          sparse-checkout: lib

      - name: Checkout Apk
        uses: actions/checkout@v4
        with:
          repository: ${{ secrets.APK }}
          ssh-key: ${{ secrets.SSH_KEY }}
          path: AzurLaneApk
          ref: ${{ matrix.apk_ref }}

      - name: Build APK
        run: |
          cp -r ../Main/lib/. libs/
          chmod +x patch_perseus.sh
          ./patch_perseus.sh
        working-directory: AzurLaneApk

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1
        with:
          packages: 'platform-tools platforms;android-34 build-tools;34.0.0'

      - name: Add Build Tools to PATH
        run: |
          echo "$ANDROID_SDK_ROOT/build-tools/34.0.0" >> $GITHUB_PATH

      - name: Zipalign and Sign
        run: |
          chmod +x zipalign_sign.sh
          ./zipalign_sign.sh
        working-directory: AzurLaneApk

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          name: ${{ steps.date.outputs.date }}_${{ matrix.config }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: |
            AzurLaneApk/build/com.${{ matrix.app_name }}.AzurLane.xapk
            AzurLaneApk/build/com.${{ matrix.app_name }}.AzurLane.patched.apk
          draft: true
          tag: test${{ matrix.config }}
          omitBody: true
